### ISSUE TITLE
No module named 'modeling'

### ISSUE THREAD

**Issue by ssppff** [nefujiangping/EncAttAgg#2]
Thank you for sharing! I can't find the 'modeling' package at runtime, and I can't install it using pip and conda. Is this package customized or installed from? Hope you can help me, thank you!

**Comment by nefujiangping** [comment]
In our work,

- For DocRED, we use pre-trained BERT ([BERT-Base, Cased](https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip)) to extract document representations and dump these features to files (*.h5). And we load the representations for training/development/test.
- For CDR, we use [PubMed pre-trained word embeddings](https://github.com/fenchri/edge-oriented-graph/blob/master/embeds/PubMed-CDR.txt); we also tried sciBERT (the same processing as DocRED), but the results are not reported in the paper.

The `modeling ` you mentioned is a part of [original bert codes](https://github.com/google-research/bert/blob/master/modeling.py), which is requried for [pre-processing](https://github.com/nefujiangping/EncAttAgg/tree/master/pre-processing) for DocRED. However, the pre-processing codes are incomplete in this repo. I'll upload the pre-processing codes later.

**Comment by nefujiangping** [comment]
Data pre-processing descriptions are updated. Please refer to README.md [data pre-processing](https://github.com/nefujiangping/EncAttAgg#data-pre-processing).

**Comment by ssppff** [comment]
Thank you for sharing!
