### ISSUE TITLE
bert_feature

### ISSUE THREAD

**Issue by ssppff** [nefujiangping/EncAttAgg#3]
Hello, thank you for your sharing. I would like to ask how to set the value of bert_feature during bert training, thank you!

**Comment by nefujiangping** [comment]
As mentioned in [data-preprocessing](https://github.com/nefujiangping/EncAttAgg/tree/master/pre-processing#docred), bert feature is only supported for DocRED dataset and the usage of bert feature follows the steps:
- [dump bert features to h5 files](https://github.com/nefujiangping/EncAttAgg/tree/master/pre-processing#docred) (`768_dev_train.h5/768_dev_dev.h5/768_dev_test.h5`)
- set `use_bert_embedding: true` in config file(https://github.com/nefujiangping/EncAttAgg/blob/d3e64a187e6568e04c5701becea14bb0bfe05f41/configs/DocRED/DocRED_EncAttAgg.yaml#L14)
- the `get_train-batches()` function will load bert features, and pass them to the model:
	+ [load h5 file](https://github.com/nefujiangping/EncAttAgg/blob/d3e64a187e6568e04c5701becea14bb0bfe05f41/trainer/DocREDFusionTrainer.py#L94) --> [construct bert feature batch](https://github.com/nefujiangping/EncAttAgg/blob/d3e64a187e6568e04c5701becea14bb0bfe05f41/trainer/DocREDFusionTrainer.py#L121) --> [yield bert feature batch](https://github.com/nefujiangping/EncAttAgg/blob/d3e64a187e6568e04c5701becea14bb0bfe05f41/trainer/DocREDFusionTrainer.py#L252) --> [pass to model forward](https://github.com/nefujiangping/EncAttAgg/blob/d3e64a187e6568e04c5701becea14bb0bfe05f41/trainer/DocREDBaseTrainer.py#L387)

However, the current way of using bert feature is ugly. Integrating bert feature by using [transformers](https://github.com/huggingface/transformers) is an elegant way. I am working on integrating [transformers](https://github.com/huggingface/transformers) to our EncAttAgg model, and I will let you know when I finished it.

**Comment by nefujiangping** [comment]
@ssppff , Sorry for the inconvenience. Integrating bert feature by using transformers is done to the [main](https://github.com/nefujiangping/EncAttAgg/tree/main) branch. Feel free to use the new codes, if you still need.
