### ISSUE TITLE
能分享一下DocRED格式的CDR数据集吗？

### ISSUE THREAD

**Issue by WarmLight7** [nefujiangping/EncAttAgg#4]

**Comment by nefujiangping** [comment]
DocRED 格式的 CDR 数据集见[这里](https://github.com/nefujiangping/EncAttAgg/tree/main/data)，处理后的 CDR 数据集`pos`为绝对位置index。

注：原始 CDR 数据集标注是`字符级别`的，论文使用了 stanford-corenlp 做 tokenize，然后将 CDR 数据标注转换为`token级别`的。其中有些样本由于 tokenize 后对齐有问题，通过人工检查修改得到。

**Comment by WarmLight7** [comment]
十分感谢您的帮助
